### ISSUE TITLE
teeth question

### ISSUE THREAD

**Issue by SSground** [SimonGiebenhain/MonoNPHM#2]
May I ask if the NPHM model has added teeth compared to Flame？

**Comment by SimonGiebenhain** [comment]
Yeah, our model can represent teeth (to some degree). You can check out some results on the [project page](https://simongiebenhain.github.io/MonoNPHM/) 

But since this area is very tricky (subject to strong lip and mouth movement, and is just partially observed due to many occulusion both during training and fitting) it is far from perfect yet.
