### ISSUE TITLE
Normals computation

### ISSUE THREAD

**Issue by elimarinoiu** [SimonGiebenhain/MonoNPHM#8]
Hi,

I tried to run the code on a video sequence of my own and the results look deformed. I noticed that after running the preprocessing code there was no normals directory generated - as I have seen in the provided FFHQ examples for which the 3d reconstructions look very good.  I have also noticed that face_normals/pretrained_models/ is empty. This directory is created when installing the associated code in running install_preprocessing_pipelines.sh but I have failed to see where this code is called - I would have expected in preprocessing/run.sh.
 
My questions are 1) am I missing something regarding the computing of the normals? Do I need to run something else and/or download the associated model? 2) Do you think the missing precomputed normals could cause the deformed results on my data?

Thanks!

**Comment by SimonGiebenhain** [comment]
Hi elimarinoiu,

I did some experiments with a normal detector with FFHQ images, but decided not to include it in the repo since I wasn't sure about the benefits. FYI you can look at this [repo](https://github.com/philgras/neural-head-avatars) for the normal detector that I used.

I never used normals for tracking in videos.
It is hard to tell what causes the complete failure that you are experiencing, but here a few things that you can look at:

- How did metrical-tracker perform on the video? Could the head pose be tracked reliably?
- Are there extreme head poses or facial expressions in the sequence? If yes does the tracking work on a subset of the sequence which excludes extreme angles/expressions?
- Are the detected landmarks, forground masks and segmentation masks looking good? (if there is a face in the background this can cause issues, but also extreme angles)
- Strong shadows are also not ideal
- Does it work to extract the first video from the video and reconstruct that single image?
- are you using `--no-intrinsics_provided` ?

Kind regards,
Simon

**Comment by elimarinoiu** [comment]
Hi Simon,

Thanks for your suggestions and clarifications!
1) The metrical tracker is not perfect, but seems ok. 
2) No extreme head poses (just having a small part of head out of the image).
3) One single face, landmarks, masks look good.
4) Shadows seem normal to me. 
5) Still looks poor on one image.
6) Yes.
The images are quite low res (224x224).
I added some screenshots of the metrical tracker and stage 1 mesh.ply. I might be missing something obvious but I didn't figure it out yet.

Best regards,
Elisabeta
<img width="947" alt="Screenshot 2024-08-06 at 14 26 17" src="https://github.com/user-attachments/assets/8baeeb94-3911-496c-8904-77118342a042">
<img width="825" alt="Screenshot 2024-08-06 at 14 31 43" src="https://github.com/user-attachments/assets/9e71dbdb-5e9c-4c63-8373-df1adbd0cded">

**Comment by SimonGiebenhain** [comment]
I see, that is defenitely not expected with that image.
Can you try again but resize the image to 512x512?
That worked for me using a screenshot from your image

**Comment by elimarinoiu** [comment]
Hi,

Thanks for your suggestion. It worked for me, as well!

Best,
Elisabeta
